services:
  postgres-db:
    image: postgres:16
    container_name: quickbite_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zeyiad123123
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/docker/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      retries: 10

  order-service:
    build: .
    image: quickbite-order-service:latest # Custom name tag added here!
    env_file:
      - .env
    environment:
      - DB_eg_HOST=postgres-db # Matched to the service name at the top
      - ARCHIVE_DB_eg_HOST=postgres-db
      - DB_ksa_HOST=postgres-db # Matched to the service name at the top
      - ARCHIVE_DB_ksa_HOST=postgres-db
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "4000:4000"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pg_data: