export const ORDER_ERRORS = {
  NOT_FOUND: 'Order not found',
  FORBIDDEN: 'You do not have access to this order',
  REGION_REQUIRED: 'X-Region header is required for this operation',
  EMPTY_ITEMS: 'Order must contain at least one item',
  BRANCH_NOT_ACCEPTING_ORDERS: 'Branch is not accepting orders',
  RESTAURANT_NOT_ACTIVE: 'Restaurant is not currently active',
  PRODUCT_NOT_AVAILABLE: 'One or more products are not available',
  INSUFFICIENT_STOCK: 'One or more items have insufficient stock',
  ADDRESS_NOT_FOUND: 'Customer address not found',
  ADDRESS_NOT_OWNED: 'Customer address does not belong to the authenticated customer',
  INVALID_STATUS_TRANSITION: 'Status transition is not allowed',
  AGENT_TRANSITION_WRONG_ENDPOINT:
    'Delivery transitions (picked, delivered) must be performed via /agent/orders/:id/{pickup,deliver}',
  CANCEL_WINDOW_EXPIRED: 'Cancellation window has passed; contact support',
  CUSTOMERS_ONLY: 'Only customers can perform this action',
  RESTAURANTS_ONLY: 'Only restaurant users can perform this action',
} as const;

export const ORDER_COLUMNS = [
  'id',
  'region',
  'public_id',
  'country_code',
  'restaurant_id',
  'restaurant_owner_id',
  'branch_id',
  'branch_lat',
  'branch_lng',
  'customer_id',
  'customer_address_id',
  'delivery_lat',
  'delivery_lng',
  'delivery_address_text_snapshot',
  'status',
  'subtotal',
  'delivery_fee',
  'service_fee',
  'total',
  'commission',
  'currency',
  'payment_method',
  'delivery_agent_id',
  'assignment_attempts',
  'last_assignment_at',
  'created_at',
  'updated_at',
  'accepted_at',
  'rejected_at',
  'ready_at',
  'assigned_at',
  'picked_at',
  'delivered_at',
  'cancelled_at',
] as const;

export const ORDER_ITEM_COLUMNS = [
  'id',
  'region',
  'order_id',
  'order_created_at',
  'product_id',
  'quantity',
  'unit_price_snapshot',
  'name_snapshot',
  'image_url_snapshot',
  'line_total',
  'created_at',
] as const;
